name: Build & Deploy App

on:
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  UV_PYTHON: 3.12
  PYTHONUTF8: 1
  FLET_CLI_NO_RICH_OUTPUT: 1
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Run tests
        run: uv run --with pytest pytest test_skincare_app.py

  build_artifacts:
    needs: run_tests
    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # -------- Android --------
          - name: android-apk
            runner: ubuntu-latest
            build_cmd: "flet build apk"
            artifact_path: build/apk
            needs_linux_deps: false

          - name: android-aab
            runner: ubuntu-latest
            build_cmd: "flet build aab"
            artifact_path: build/aab
            needs_linux_deps: false

          # -------- Windows --------
          - name: windows
            runner: windows-latest
            build_cmd: "flet build windows"
            artifact_path: build/windows
            needs_linux_deps: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Install Linux dependencies
        if: matrix.needs_linux_deps
        shell: bash
        run: |
            sudo apt update --allow-releaseinfo-change
            sudo apt-get install -y --no-install-recommends \
              clang ninja-build libgtk-3-dev libasound2-dev libmpv-dev mpv \
              libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev \
              gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly \
              gstreamer1.0-libav gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 \
              gstreamer1.0-qt5 gstreamer1.0-pulseaudio pkg-config libsecret-1-0 libsecret-1-dev
            sudo apt-get clean

      - name: Build app
        shell: bash
        run: |
          uvx ${{ matrix.build_cmd }} --module-name skincare_app --yes --verbose

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}-build-artifact
          path: ${{ matrix.artifact_path }}
          if-no-files-found: error
          overwrite: false

  build_web:
    needs: run_tests
    name: Build Web App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        
      - name: Build web
        shell: bash
        run: |
          uvx flet build web --module-name skincare_app --yes --verbose --base-url ${GITHUB_REPOSITORY#*/} --route-url-strategy hash
          
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/web
          name: github-pages
          retention-days: 20

  deploy_web:
    name: Deploy to GitHub Pages
    needs: build_web
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4